In [1]:
import numpy as np

1.SORU

In [2]:
arr1 = np.arange(0,30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
arr2 = arr1.reshape(15,2)
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2.SORU

In [4]:
arr3 = np.arange(60)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [6]:
arr4 = arr3.reshape(2,5,6)
arr4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [7]:
arr4.ndim

3

In [9]:
arr4.shape

(2, 5, 6)

3.SORU

In [10]:
arr5 = np.random.randint(0,10, size= (4,3))
arr5

array([[9, 9, 9],
       [9, 8, 3],
       [0, 9, 7],
       [1, 6, 0]])

In [15]:
arr6 = arr5.reshape(-1)
arr6

array([9, 9, 9, 9, 8, 3, 0, 9, 7, 1, 6, 0])

In [16]:
arr6.ndim

1

In [17]:
arr6.shape

(12,)

4.SORU

In [18]:
arr7 = np.arange(20).reshape(4,5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
for x in arr7:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [20]:
for x in np.nditer(arr7):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


5.SORU

In [26]:
arr8 = np.array([5,10,15,20,25,30])
arr9 = np.array([1,2,3,4,5,6])

In [27]:
arr8 + arr9

array([ 6, 12, 18, 24, 30, 36])

In [28]:
arr8 - arr9

array([ 4,  8, 12, 16, 20, 24])

In [29]:
arr8 * arr9

array([  5,  20,  45,  80, 125, 180])

In [31]:
arr8 // arr9

array([5, 5, 5, 5, 5, 5])

6.SORU

In [34]:
arr10 = np.random.randint(0,101,10)
arr10

array([20, 87, 78, 68, 49, 93, 78, 25,  4, 28])

In [35]:
arr10.sum()

530

In [36]:
arr10.mean()

53.0

In [37]:
arr10.var()

914.6

In [38]:
arr10.std()

30.242354405700624

7.SORU

In [40]:
arr11 = np.arange(0,20)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
arr12 = np.arange(500,531)
arr12

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [42]:
np.concatenate([arr11,arr12])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8.SORU

In [44]:
arr13 = np.arange(15,51)
arr13

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50])

In [45]:
arr14 = np.arange(10,101)
arr14

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [46]:
arr15 = np.concatenate([arr13,arr14] , axis = 0 )
arr15

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [47]:
arr15[25:51] = 888
arr15

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9.SORU


In [48]:
arr16 = np.random.randint(0,40, size=(8,5))
arr16

array([[ 9, 34, 38, 12, 35],
       [27, 31,  1,  6, 28],
       [17, 39, 27, 38,  3],
       [ 3, 30, 16, 20, 16],
       [16, 36, 39, 32, 37],
       [29,  8, 16,  0, 15],
       [30,  6,  6, 10, 16],
       [30, 30, 32, 30,  7]])

In [49]:
arr17 = np.random.randint(320,360, size=(8,5))
arr17

array([[326, 348, 323, 354, 330],
       [327, 326, 326, 329, 347],
       [334, 349, 320, 346, 345],
       [321, 357, 357, 340, 356],
       [348, 325, 329, 338, 352],
       [348, 343, 354, 332, 345],
       [336, 324, 340, 345, 341],
       [348, 342, 335, 320, 329]])

In [50]:
np.concatenate([arr16,arr17] , axis = 0)

array([[  9,  34,  38,  12,  35],
       [ 27,  31,   1,   6,  28],
       [ 17,  39,  27,  38,   3],
       [  3,  30,  16,  20,  16],
       [ 16,  36,  39,  32,  37],
       [ 29,   8,  16,   0,  15],
       [ 30,   6,   6,  10,  16],
       [ 30,  30,  32,  30,   7],
       [326, 348, 323, 354, 330],
       [327, 326, 326, 329, 347],
       [334, 349, 320, 346, 345],
       [321, 357, 357, 340, 356],
       [348, 325, 329, 338, 352],
       [348, 343, 354, 332, 345],
       [336, 324, 340, 345, 341],
       [348, 342, 335, 320, 329]])

In [51]:
np.concatenate([arr16,arr17] , axis = 1)

array([[  9,  34,  38,  12,  35, 326, 348, 323, 354, 330],
       [ 27,  31,   1,   6,  28, 327, 326, 326, 329, 347],
       [ 17,  39,  27,  38,   3, 334, 349, 320, 346, 345],
       [  3,  30,  16,  20,  16, 321, 357, 357, 340, 356],
       [ 16,  36,  39,  32,  37, 348, 325, 329, 338, 352],
       [ 29,   8,  16,   0,  15, 348, 343, 354, 332, 345],
       [ 30,   6,   6,  10,  16, 336, 324, 340, 345, 341],
       [ 30,  30,  32,  30,   7, 348, 342, 335, 320, 329]])

10.SORU

In [52]:
np.concatenate([arr16,arr17] , axis = 2)

AxisError: ignored

In [53]:
np.stack([arr16,arr17] , axis = 2)

array([[[  9, 326],
        [ 34, 348],
        [ 38, 323],
        [ 12, 354],
        [ 35, 330]],

       [[ 27, 327],
        [ 31, 326],
        [  1, 326],
        [  6, 329],
        [ 28, 347]],

       [[ 17, 334],
        [ 39, 349],
        [ 27, 320],
        [ 38, 346],
        [  3, 345]],

       [[  3, 321],
        [ 30, 357],
        [ 16, 357],
        [ 20, 340],
        [ 16, 356]],

       [[ 16, 348],
        [ 36, 325],
        [ 39, 329],
        [ 32, 338],
        [ 37, 352]],

       [[ 29, 348],
        [  8, 343],
        [ 16, 354],
        [  0, 332],
        [ 15, 345]],

       [[ 30, 336],
        [  6, 324],
        [  6, 340],
        [ 10, 345],
        [ 16, 341]],

       [[ 30, 348],
        [ 30, 342],
        [ 32, 335],
        [ 30, 320],
        [  7, 329]]])

11.SORU

In [55]:
arr18 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr18

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [56]:
np.where(arr18 == 5)

(array([ 5, 13]),)

12.SORU

In [57]:
np.where(arr18%2 == 0 )

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13.SORU

In [58]:
np.where(arr18>4 )

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14.SORU

In [59]:
np.where(arr18%5 == 0 )

(array([ 1,  2,  5, 13]),)

15.SORU

In [60]:
np.random.randint(low = 85 , high = 101 , size = 1)

array([91])

16.SORU

In [61]:
np.random.randint(low = 10 , high = 100 , size = (3,3))

array([[25, 14, 11],
       [67, 56, 24],
       [31, 25, 44]])

17.SORU

In [63]:
arr19 = np.arange(35,61)
arr19

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [64]:
np.random.choice(arr19)

53

18.SORU

In [65]:
arr20 = np.random.choice([3,8,10,53], size=(2,5))
arr20

array([[ 8, 10, 10, 53,  8],
       [10, 53,  8, 53, 53]])