# NumPy Exercises

Bu zamana kadar gördüğümüz konularla alakalı bilgilerimizi test edelim

<div class="alert alert-danger" style="margin: 10px"><strong>Uyarı!</strong> Output'un üstündeki kod hücrelerini çalıştırmayın !, <br>Aksi takdirde notebooktaki cevap outputlarını kaybedebilirsiniz!</div>

#### 1. NumPy kütüphanesi np kısaltması ile import edin

In [2]:
import numpy as np

#### 2. 10 tane 0 değerinden oluşan bir array oluşturun

In [14]:
np.zeros(10 , dtype= 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# Bu hücreye kod yazıp çalıştırma !

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3. 10 tane 1 değerinden oluşan bir array oluşturun

In [15]:
np.ones(10 , dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
# Bu hücreye kod yazıp çalıştırma !

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 4. 10 tane 5 değerinden oluşan bir array oluşturun

In [16]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım

In [17]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [3]:
# Bu hücreye kod yazıp çalıştırma !

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [18]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
# Bu hücreye kod yazıp çalıştırma !

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Bu hücreye kod yazıp çalıştırma !

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 3x3 boyutlarında birim matris oluşturun

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Bu hücreye kod yazıp çalıştırma !

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun. <br><br>&emsp;NOT: Değerler random seçildiği için sizin sonucunuz aşağıdaki çıktıdan farklı olacaktır

In [21]:
np.random.rand(1)

array([0.06852291])

In [7]:
# Bu hücreye kod yazıp çalıştırma !

array([0.20308617])

#### 10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım. <br><br>&emsp;&ensp;NOT: Sizin cevabınız aşağıdaki çıktıdan farklı olacaktır

In [22]:
np.random.rand(25)

array([0.91557643, 0.94207685, 0.22446821, 0.35224013, 0.42317642,
       0.40986093, 0.18796705, 0.83615364, 0.76507048, 0.84219931,
       0.84100268, 0.79529007, 0.20997222, 0.974902  , 0.59770174,
       0.16898819, 0.00159014, 0.45905477, 0.47709008, 0.05839521,
       0.71015681, 0.30578823, 0.90233185, 0.65387949, 0.09672371])

In [8]:
# Bu hücreye kod yazıp çalıştırma !

array([0.57542279, 0.41789832, 0.17110283, 0.58013565, 0.50461388,
       0.6205302 , 0.37021405, 0.80967232, 0.11935321, 0.53370735,
       0.85578729, 0.48367325, 0.15103948, 0.45330415, 0.00643794,
       0.84074462, 0.7106187 , 0.62071192, 0.07329613, 0.10427419,
       0.21857469, 0.93021856, 0.53704694, 0.62644154, 0.42573388])

#### 11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

In [12]:
np.arange(0.01 , 1.01, 0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [9]:
# Bu hücreye kod yazıp çalıştırma !

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### 12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [10]:
# Bu hücreye kod yazıp çalıştırma !

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy Indexing and Selection

Aşağıdaki matris sıradaki sorular için bizim başlangıç matrisimiz. (Aşağıdaki kod hücresini çalıştırarak devam edin.), devamında sorduğumuz soruları cevaplamaya çalışın:


In [11]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Aşağıda verilen matrisleri oluşturmaya çalışın.<br><br>&emsp;&ensp;Çıktıların üstündeki kod hücresini çalıştırmayın, aksi takdirde çıktıları göremezsiniz

In [ ]:
# Kodlarınızı buraya yazın

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [28]:
mat[3,4]

20

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

20

#### 15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[ 2],
       [ 7],
       [12]])

#### 16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [23]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([21, 22, 23, 24, 25])

#### 17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [24]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Mat arrayindeki bütün değerlerin toplamını bulun

In [25]:
mat.sum()

325

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

325

#### 19. Mat arrayindeki değerlerin standart sapmasını bulun

In [26]:
mat.std()

7.211102550927978

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

7.211102550927978

#### 20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun

In [27]:
toplam = np.vstack(sum(mat)).reshape(-1)
toplam

array([55, 60, 65, 70, 75])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([55, 60, 65, 70, 75])

# Tebrikler, NumPy temelleri öğrenilmiş!