In [1]:
import numpy as np

1.SORU

In [2]:
arr3d = np.array([[ [1,2,3] ,[4,5,6] , [10,25,35] ,[40,50,60] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]]])

In [3]:
arr3d.ndim

3

2.SORU

In [5]:
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3.SORU

In [8]:
np.linspace(50,500,91, dtype = int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4.SORU

In [11]:
np.logspace(10**2,10*5, 8)

array([1.00000000e+100, 7.19685673e+092, 5.17947468e+085, 3.72759372e+078,
       2.68269580e+071, 1.93069773e+064, 1.38949549e+057, 1.00000000e+050])

5.SORU

In [12]:
np.random.randint(0,9 , (3,3))

array([[7, 7, 8],
       [2, 6, 1],
       [8, 7, 6]])

6.SORU

In [13]:
np.zeros((6,6) , dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7.SORU

In [14]:
np.ones((4,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8.SORU

In [15]:
np.eye(8 , dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9.SORU

10.SORU

In [16]:
np.random.rand(6)

array([0.01109523, 0.53399792, 0.14868446, 0.10979182, 0.07578623,
       0.93210773])

11.SORU

In [17]:
np.random.randint(50,101, size=(5,2)) 

array([[ 97,  60],
       [ 87,  58],
       [100,  59],
       [ 60,  99],
       [ 92,  96]])

12.SORU

In [19]:
arr4 = np.random.randint(100,1000, size=(2,5,5)) 
arr4

array([[[193, 676, 962, 731, 564],
        [314, 820, 404, 235, 252],
        [677, 765, 271, 673, 809],
        [695, 139, 943, 691, 880],
        [720, 901, 643, 667, 345]],

       [[892, 537, 950, 839, 228],
        [593, 225, 750, 886, 427],
        [772, 597, 388, 374, 397],
        [831, 974, 601, 626, 646],
        [365, 830, 914, 444, 468]]])

In [20]:
arr4.ndim

3

In [21]:
arr4.shape

(2, 5, 5)

13.SORU

In [22]:
arr5 = np.random.randint(0,100,10)
arr5

array([27, 66, 81, 54, 19, 55, 51, 67, 53, 75])

In [24]:
arr5.max()

81

In [25]:
arr5.min()

19

In [26]:
arr5.argmin()

4

14.SORU

In [27]:
arr6 = np.random.randint(300,501, size=(2,2,5)) 
arr6

array([[[320, 449, 333, 452, 391],
        [380, 465, 377, 350, 390]],

       [[361, 467, 422, 375, 470],
        [347, 337, 454, 454, 482]]])

In [28]:
arr6.max()

482

In [29]:
arr6.min()

320

In [30]:
arr6[1,1,4]

482

In [31]:
arr6[0,0,0]

320

15.SORU

In [33]:
arr7 = np.arange(0,51)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [35]:
arr8 = arr7[20:36] = 500
arr8

500